from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class PlannedAction:
    """Represents a single action generated by the LLM."""

    name: str
    locator: Optional[Dict[str, Any]] = None
    value: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

    @classmethod
    def from_dict(cls, payload: Dict[str, Any]) -> "PlannedAction":
        return cls(
            name=payload.get("name") or payload.get("type") or "noop",
            locator=payload.get("locator"),
            value=payload.get("value"),
            metadata=payload.get("metadata", {}),
        )

    def describe(self) -> str:
        locator = self.locator or {}
        locator_hint = f"{locator.get('strategy')}={locator.get('value')}" if locator else "none"
        return f"{self.name} (locator: {locator_hint}, value={self.value})"


@dataclass
class PlanResponse:
    actions: List[PlannedAction]
    request_refresh: bool = True
    thought: str = ""
    raw: Dict[str, Any] = field(default_factory=dict)

    @classmethod
    def from_payload(cls, payload: Dict[str, Any]) -> "PlanResponse":
        actions = [PlannedAction.from_dict(item) for item in payload.get("actions", [])]
        return cls(
            actions=actions,
            request_refresh=bool(payload.get("request_refresh", True)),
            thought=payload.get("thought", ""),
            raw=payload,
        )
